In [1]:
import csv
import numpy as np
import pandas as pd
from konlpy.tag import Okt
#df2018=pd.read_pickle("mdata2018.pkl")
#df2018=pd.read_csv("mdata2018.csv")
data2018=pd.read_csv("DTM2018.csv")

In [2]:
data2018=data2018.drop([data2018.columns[0]], axis=1)
data2018

,가가,가감,가건물,가게,가격,가격결정,가격담합,가격표,가결,가계,...,힘안,힘앞,힘자랑,힘줄,힙내세,힙니,힙들어,힙듭니,힙병,힙합
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15719,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15720,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15721,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15722,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15723,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
data2018['한국']

0        0
1        0
2        0
3        0
4        0
        ..
15719    0
15720    0
15721    1
15722    0
15723    7
Name: 한국, Length: 15724, dtype: int64

In [4]:
for i in range(0,15724):
    data2018['대한민국'][i]=data2018['대한민국'][i]+data2018['한국'][i]

In [5]:
data2018=data2018.drop(['한국'],axis='columns')

In [6]:
df2018_sum=data2018.sum()
data2018=data2018.transpose()
df2018_sum=df2018_sum.T
col=data2018.index
col

Index(['가가', '가감', '가건물', '가게', '가격', '가격결정', '가격담합', '가격표', '가결', '가계',
       ...
       '힘안', '힘앞', '힘자랑', '힘줄', '힙내세', '힙니', '힙들어', '힙듭니', '힙병', '힙합'],
      dtype='object', length=39599)

In [7]:
df2018_sum=df2018_sum.to_numpy()

In [8]:
from math import log
def idf(t):
    df=df2018_sum[t]
    return log(15724/(df+1))

In [ ]:
for d in range(len(data2018)):
    for t in range(len(data2018[0])):
        data2018[d][t]=data2018[d][t]+idf(d)

In [ ]:
data2018

In [ ]:
df_tfidf=pd.Dataframe(data2018, index=col)

In [ ]:
df_tfidf